# Generated by Django 3.1.3 on 2022-04-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice',
        ),
        migrations.AddField(
            model_name='choice',
            name='content',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
